package ReverseModule;


/**
* ReverseModule/Reverse.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Friday, 8 May, 2026 6:23:46 PM IST
*/

public interface Reverse extends ReverseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Reverse
